- name: Listen for Grafana Webhooks
  hosts: all

  sources:
    - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000

  rules:
    - name: Display contents
      condition: event.payload.message is defined

      action:
        debug:
          msg: "Received"
