---
- name: Automatic Remediation of a servers - EDA Server Watchdog
  hosts: all
  sources:
    - name: thisis watchdog------
      ansible.eda.file_watch:
        path: "/var/games/"
        recursive: true
        ignore_regexes: ['.*\.pytest.*', '.*__pycache__.*', '.*/.git.*']
  rules:
    - name: Notify on file changes
      condition: event.type in ["created"]
      action:
        run_job_template:
          name: Demo Job Template
          organization: "Default"
