---
- name: Monitor /opt/ directory for changes
  hosts: localhost
  sources:
    - ansible.eda.file_watch:
        path: /mnt/
        recursive: false
        debounce_seconds: 5  # Prevents event flooding
        ignore_regexes: ['.*\\.pytest.*', '.*__pycache__.*', '.*/.git.*']
  rules:
    - name: Notify on file changes
      condition: event.type in ["created"]
      action:
        run_job_template:
          name: Demo Job Template
