---
 - name: Hello Controller 
   hosts: all
   sources:
     - ansible.eda.range:
         limit: 5

   rules:
     - name: "Run job template"
       contition: event.target_os == "linux"
       action:
         debug:
